name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloudrun-deploy-demo

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cloudrun-deploy-demo \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloudrun-deploy-demo \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
